###
GET http://localhost:8888/api/v1/student



###
PUT http://localhost:8888/api/v1/student/1?name=Mariam&email=mariam.jamal@gmail.com
Content-Type: application/json

###
POST http://localhost:8888/api/v1/student
Content-Type: application/json

{
  "name": "hilal",
  "email": "amina.ayadi@gmail.com",
  "dob": "2000-12-17"
}


### 2023.08.30
###
DELETE http://localhost:8888/api/v1/student/1

